model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    image_key: image
#    ckpt_path: /root/autodl-tmp/synthesis/logs/2022-05-24T15-44-53_cityscapes_vqgan_w512_h256_embdim_256/checkpoints/last.ckpt
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 128 #being changed
      out_ch: 128 #being changed
      ch: 128
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      real_in_channels: 3
      real_out_ch: 3

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    train:
      target: taming.data.cityscapes_512.Examples # adjust
      params:
        data_csv: "/root/scripts/taming-cityscapes/train.txt"
        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit/train"
        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine/train"
    validation:
      target: taming.data.cityscapes_512.Examples # adjust
      params:
        data_csv: "/root/scripts/taming-cityscapes/val.txt"
        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit/val"
        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine/val"