model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    first_stage_key: image
    cond_stage_key: segmentation
    edge_stage_key: instance
    use_edge: True
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 8192
        block_size: 768
        n_layer: 24
        n_head: 16
        n_embd: 1024
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
#        ckpt_path: /root/autodl-tmp/synthesis/logs/2022-05-24T15-44-53_cityscapes_vqgan_w512_h256_embdim_256_77_epoch/checkpoints/last.ckpt
        embed_dim: 256   #changed
        n_embed: 8192
        image_key: image
        ddconfig:
          double_z: False
          z_channels: 256 #changed
          resolution: 256 #changed
          in_channels: 128
          out_ch: 128
          ch: 128
          ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
          real_in_channels: 3
          real_out_ch: 3
        lossconfig:
          target: taming.modules.losses.DummyLoss

    cond_stage_config:
      target: taming.models.vqgan.VQModel
      params:
#        ckpt_path: /root/autodl-tmp/synthesis/logs/2022-05-25T10-09-40_cityscapes_cond_vqgan_w512_h256_embdim_256_50_epoch/checkpoints/last.ckpt
        embed_dim: 256 #changed
        n_embed: 1024
        image_key: segmentation
        ddconfig:
          double_z: false
          z_channels: 256 #changed
          resolution: 256 #changed
          in_channels: 128
          out_ch: 128
          ch: 128
          ch_mult: [1, 1, 2, 2, 4]
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
          real_in_channels: 34
          real_out_ch: 34
        lossconfig:
          target: taming.modules.losses.DummyLoss

    edge_stage_config:
      target: taming.models.vqgan.VQModel
      params:
#        ckpt_path: /root/autodl-tmp/synthesis/logs/2022-05-25T14-23-51_cityscapes_edge_vqgan_w512_h256_embdim_256_46_epoch/checkpoints/last.ckpt
        embed_dim: 256 #changed
        n_embed: 1024
        image_key: instance
        ddconfig:
          double_z: false
          z_channels: 256 #changed
          resolution: 256 #changed
          in_channels: 128
          out_ch: 128
          ch: 128
          ch_mult: [1, 1, 2, 2, 4]
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
          real_in_channels: 2
          real_out_ch: 2
        lossconfig:
          target: taming.modules.losses.DummyLoss

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 6
#    train:
#      target: taming.data.cityscapes_512_with_semantic_map.Examples # adjust
#      params:
#        data_csv: "/root/scripts/taming-cityscapes/train_val.txt"
#        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit"
#        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine"
#    validation:
#      target: taming.data.cityscapes_512_with_semantic_map.Examples
#      params:
#        data_csv: "/root/scripts/taming-cityscapes/val.txt"
#        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit/val"
#        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine/val"
    test:
      target: taming.data.cityscapes_512_with_semantic_map_test.Examples # adjust
      params:
        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit"