model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 512
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: taming.data.cityscapes.Examples # adjust
      params:
        size: 256 #changed
        random_crop: True
        data_csv: "/root/scripts/taming-cityscapes/train.txt"
        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit/train"
        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine/train"
    validation:
      target: taming.data.cityscapes.Examples # adjust
      params:
        size: 256 #changed
        random_crop: True
        data_csv: "/root/scripts/taming-cityscapes/val.txt"
        data_root: "/root/autodl-tmp/cityscapes_segformer/leftImg8bit/val"
        segmentation_root: "/root/autodl-tmp/cityscapes_segformer/gtFine/val"